/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CronCreateRequest, CronHistoryRequest, CronHistoryResult, CronIdRequest, CronListRequest, CronListResult, CronMutationResult, CronUpdateRequest } from 'dsh-cron/remote-types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$63726f6e {
    create: (request: CronCreateRequest) => Promise<RemoteResult<CronMutationResult>>
    delete: (request: CronIdRequest) => Promise<RemoteResult<CronMutationResult>>
    history: (request: CronHistoryRequest) => Promise<RemoteResult<CronHistoryResult>>
    list: (request: CronListRequest) => Promise<RemoteResult<CronListResult>>
    pause: (request: CronIdRequest) => Promise<RemoteResult<CronMutationResult>>
    resume: (request: CronIdRequest) => Promise<RemoteResult<CronMutationResult>>
    update: (request: CronUpdateRequest) => Promise<RemoteResult<CronMutationResult>>
  }
  interface TypertRemoteMap {
    'cron/create': (request: CronCreateRequest) => Promise<RemoteResult<CronMutationResult>>
    'cron/delete': (request: CronIdRequest) => Promise<RemoteResult<CronMutationResult>>
    'cron/history': (request: CronHistoryRequest) => Promise<RemoteResult<CronHistoryResult>>
    'cron/list': (request: CronListRequest) => Promise<RemoteResult<CronListResult>>
    'cron/pause': (request: CronIdRequest) => Promise<RemoteResult<CronMutationResult>>
    'cron/resume': (request: CronIdRequest) => Promise<RemoteResult<CronMutationResult>>
    'cron/update': (request: CronUpdateRequest) => Promise<RemoteResult<CronMutationResult>>
  }
  interface TypertRemoteNamespaceMap {
    'cron': TypertRemoteNamespace$63726f6e
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
