/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_cron_cron_create_parameter_0$schema = z.intersection(z.intersection(z.object({
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
}), z.object({
  'executionMode': z.union([z.literal("existing_session"), z.literal("new_session")]).readonly(),
})), z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}))
const dsh_cron_cron_create_result$schema = z.union([z.intersection(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
  'createdFromSessionId': z.string().readonly(),
  'state': z.union([z.literal("deleted"), z.literal("active"), z.literal("paused")]).readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'deletedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.literal("existing_session").readonly(),
  'targetSessionId': z.string().readonly(),
})), z.intersection(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
  'createdFromSessionId': z.string().readonly(),
  'state': z.union([z.literal("deleted"), z.literal("active"), z.literal("paused")]).readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'deletedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.literal("new_session").readonly(),
  'agentPresetId': z.string().readonly(),
}))])
const dsh_cron_cron_delete_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'cronId': z.string().readonly(),
})
const dsh_cron_cron_delete_result$schema = z.union([z.intersection(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
  'createdFromSessionId': z.string().readonly(),
  'state': z.union([z.literal("deleted"), z.literal("active"), z.literal("paused")]).readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'deletedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.literal("existing_session").readonly(),
  'targetSessionId': z.string().readonly(),
})), z.intersection(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
  'createdFromSessionId': z.string().readonly(),
  'state': z.union([z.literal("deleted"), z.literal("active"), z.literal("paused")]).readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'deletedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.literal("new_session").readonly(),
  'agentPresetId': z.string().readonly(),
}))])
const dsh_cron_cron_history_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'cronId': z.string().readonly(),
  'cursor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
})
const dsh_cron_cron_history_result$schema = z.object({
  'items': z.array(z.object({
  'id': z.string().readonly(),
  'cronId': z.string().readonly(),
  'trigger': z.union([z.literal("on_time"), z.literal("startup_catch_up"), z.literal("pending_after_run")]).readonly(),
  'scheduledFor': z.union([z.undefined(), z.string()]).readonly().optional(),
  'delayed': z.boolean().readonly(),
  'coalescedThrough': z.union([z.undefined(), z.string()]).readonly().optional(),
  'state': z.union([z.literal("queued"), z.literal("running"), z.literal("waiting_approval"), z.literal("succeeded"), z.literal("failed"), z.literal("cancelled"), z.literal("coalesced")]).readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sessionRequestId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'failureCode': z.union([z.undefined(), z.literal("cron_not_found"), z.literal("invalid_expression"), z.literal("invalid_timezone"), z.literal("workspace_context_unavailable"), z.literal("target_session_unavailable"), z.literal("agent_preset_unavailable"), z.literal("model_unavailable"), z.literal("prompt_rejected"), z.literal("persistence_unavailable"), z.literal("internal_error")]).readonly().optional(),
  'startedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
  'finishedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'nextCursor': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const dsh_cron_cron_list_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'scope': z.union([z.literal("related"), z.literal("all"), z.literal("deleted")]).readonly(),
})
const dsh_cron_cron_list_result$schema = z.array(z.union([z.intersection(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
  'createdFromSessionId': z.string().readonly(),
  'state': z.union([z.literal("deleted"), z.literal("active"), z.literal("paused")]).readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'deletedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.literal("existing_session").readonly(),
  'targetSessionId': z.string().readonly(),
})), z.intersection(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
  'createdFromSessionId': z.string().readonly(),
  'state': z.union([z.literal("deleted"), z.literal("active"), z.literal("paused")]).readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'deletedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.literal("new_session").readonly(),
  'agentPresetId': z.string().readonly(),
}))]))
const dsh_cron_cron_pause_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'cronId': z.string().readonly(),
})
const dsh_cron_cron_pause_result$schema = z.union([z.intersection(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
  'createdFromSessionId': z.string().readonly(),
  'state': z.union([z.literal("deleted"), z.literal("active"), z.literal("paused")]).readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'deletedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.literal("existing_session").readonly(),
  'targetSessionId': z.string().readonly(),
})), z.intersection(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
  'createdFromSessionId': z.string().readonly(),
  'state': z.union([z.literal("deleted"), z.literal("active"), z.literal("paused")]).readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'deletedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.literal("new_session").readonly(),
  'agentPresetId': z.string().readonly(),
}))])
const dsh_cron_cron_resume_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'cronId': z.string().readonly(),
})
const dsh_cron_cron_resume_result$schema = z.union([z.intersection(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
  'createdFromSessionId': z.string().readonly(),
  'state': z.union([z.literal("deleted"), z.literal("active"), z.literal("paused")]).readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'deletedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.literal("existing_session").readonly(),
  'targetSessionId': z.string().readonly(),
})), z.intersection(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
  'createdFromSessionId': z.string().readonly(),
  'state': z.union([z.literal("deleted"), z.literal("active"), z.literal("paused")]).readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'deletedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.literal("new_session").readonly(),
  'agentPresetId': z.string().readonly(),
}))])
const dsh_cron_cron_update_parameter_0$schema = z.intersection(z.intersection(z.object({
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
  'expression': z.union([z.undefined(), z.string()]).readonly().optional(),
  'timezone': z.union([z.undefined(), z.string()]).readonly().optional(),
  'prompt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.union([z.undefined(), z.literal("existing_session"), z.literal("new_session")]).readonly().optional(),
})), z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'cronId': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
}))
const dsh_cron_cron_update_result$schema = z.union([z.intersection(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
  'createdFromSessionId': z.string().readonly(),
  'state': z.union([z.literal("deleted"), z.literal("active"), z.literal("paused")]).readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'deletedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.literal("existing_session").readonly(),
  'targetSessionId': z.string().readonly(),
})), z.intersection(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'name': z.string().readonly(),
  'expression': z.string().readonly(),
  'timezone': z.string().readonly(),
  'prompt': z.string().readonly(),
  'createdFromSessionId': z.string().readonly(),
  'state': z.union([z.literal("deleted"), z.literal("active"), z.literal("paused")]).readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'deletedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'executionMode': z.literal("new_session").readonly(),
  'agentPresetId': z.string().readonly(),
}))])

export const TYPERT = {
  package: 'dsh-cron',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-cron#cron/create',
      service: 'cron',
      namespace: 'cron',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-cron/remote-types#CronCreateRequest',
            schema: dsh_cron_cron_create_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-cron/remote-types#CronMutationResult',
        schema: dsh_cron_cron_create_result$schema,
      },
      sourceLocation: {"file":"packages/cron/src/remote.ts","line":34,"column":3},
    },
    {
      id: 'dsh-cron#cron/delete',
      service: 'cron',
      namespace: 'cron',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-cron/remote-types#CronIdRequest',
            schema: dsh_cron_cron_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-cron/remote-types#CronMutationResult',
        schema: dsh_cron_cron_delete_result$schema,
      },
      sourceLocation: {"file":"packages/cron/src/remote.ts","line":56,"column":3},
    },
    {
      id: 'dsh-cron#cron/history',
      service: 'cron',
      namespace: 'cron',
      method: 'history',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-cron/remote-types#CronHistoryRequest',
            schema: dsh_cron_cron_history_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-cron/remote-types#CronHistoryResult',
        schema: dsh_cron_cron_history_result$schema,
      },
      sourceLocation: {"file":"packages/cron/src/remote.ts","line":28,"column":3},
    },
    {
      id: 'dsh-cron#cron/list',
      service: 'cron',
      namespace: 'cron',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-cron/remote-types#CronListRequest',
            schema: dsh_cron_cron_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-cron/remote-types#CronListResult',
        schema: dsh_cron_cron_list_result$schema,
      },
      sourceLocation: {"file":"packages/cron/src/remote.ts","line":23,"column":3},
    },
    {
      id: 'dsh-cron#cron/pause',
      service: 'cron',
      namespace: 'cron',
      method: 'pause',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-cron/remote-types#CronIdRequest',
            schema: dsh_cron_cron_pause_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-cron/remote-types#CronMutationResult',
        schema: dsh_cron_cron_pause_result$schema,
      },
      sourceLocation: {"file":"packages/cron/src/remote.ts","line":46,"column":3},
    },
    {
      id: 'dsh-cron#cron/resume',
      service: 'cron',
      namespace: 'cron',
      method: 'resume',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-cron/remote-types#CronIdRequest',
            schema: dsh_cron_cron_resume_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-cron/remote-types#CronMutationResult',
        schema: dsh_cron_cron_resume_result$schema,
      },
      sourceLocation: {"file":"packages/cron/src/remote.ts","line":51,"column":3},
    },
    {
      id: 'dsh-cron#cron/update',
      service: 'cron',
      namespace: 'cron',
      method: 'update',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-cron/remote-types#CronUpdateRequest',
            schema: dsh_cron_cron_update_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-cron/remote-types#CronMutationResult',
        schema: dsh_cron_cron_update_result$schema,
      },
      sourceLocation: {"file":"packages/cron/src/remote.ts","line":40,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
