/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { MailSettingsSaveRequest, MailSettingsSaveResult } from 'dsh-mail-plugin/remote-types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d61696c53657474696e6773 {
    save: (request: MailSettingsSaveRequest) => Promise<RemoteResult<MailSettingsSaveResult>>
  }
  interface TypertRemoteMap {
    'mailSettings/save': (request: MailSettingsSaveRequest) => Promise<RemoteResult<MailSettingsSaveResult>>
  }
  interface TypertRemoteNamespaceMap {
    'mailSettings': TypertRemoteNamespace$6d61696c53657474696e6773
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
