/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_mail_mailSettings_load_result$schema = z.object({
  'settings': z.object({
  'username': z.string(),
  'passwordEnv': z.string(),
  'mailbox': z.string(),
  'archiveMailbox': z.string(),
  'allowDelete': z.boolean(),
  'imap': z.object({
  'host': z.string(),
  'port': z.number(),
  'secure': z.boolean(),
}),
  'smtp': z.object({
  'host': z.string(),
  'port': z.number(),
  'secure': z.boolean(),
}),
}).readonly(),
})
const dsh_mail_mailSettings_save_parameter_0$schema = z.object({
  'settings': z.object({
  'username': z.string(),
  'passwordEnv': z.string(),
  'mailbox': z.string(),
  'archiveMailbox': z.string(),
  'allowDelete': z.boolean(),
  'imap': z.object({
  'host': z.string(),
  'port': z.number(),
  'secure': z.boolean(),
}),
  'smtp': z.object({
  'host': z.string(),
  'port': z.number(),
  'secure': z.boolean(),
}),
}).readonly(),
})
const dsh_mail_mailSettings_save_result$schema = z.object({
  'settings': z.object({
  'username': z.string(),
  'passwordEnv': z.string(),
  'mailbox': z.string(),
  'archiveMailbox': z.string(),
  'allowDelete': z.boolean(),
  'imap': z.object({
  'host': z.string(),
  'port': z.number(),
  'secure': z.boolean(),
}),
  'smtp': z.object({
  'host': z.string(),
  'port': z.number(),
  'secure': z.boolean(),
}),
}).readonly(),
})

export const TYPERT = {
  package: 'dsh-mail',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-mail#mailSettings/load',
      service: 'mailSettings',
      namespace: 'mailSettings',
      method: 'load',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-mail/remote-types#MailSettingsSaveResult',
        schema: dsh_mail_mailSettings_load_result$schema,
      },
      sourceLocation: {"file":"packages/mail/src/index.ts","line":69,"column":3},
    },
    {
      id: 'dsh-mail#mailSettings/save',
      service: 'mailSettings',
      namespace: 'mailSettings',
      method: 'save',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-mail/remote-types#MailSettingsSaveRequest',
            schema: dsh_mail_mailSettings_save_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-mail/remote-types#MailSettingsSaveResult',
        schema: dsh_mail_mailSettings_save_result$schema,
      },
      sourceLocation: {"file":"packages/mail/src/index.ts","line":77,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
