/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_nextcloud_nextcloudSettings_load_result$schema = z.object({
  'settings': z.object({
  'serverUrl': z.string().readonly(),
  'username': z.string().readonly(),
  'accessMode': z.union([z.literal("all"), z.literal("allowlist")]).readonly(),
  'allowedRoots': z.array(z.string()).readonly(),
  'allowDelete': z.boolean().readonly(),
  'allowHttp': z.boolean().readonly(),
  'skipTlsVerify': z.boolean().readonly(),
}).readonly(),
})
const dsh_nextcloud_nextcloudSettings_save_parameter_0$schema = z.object({
  'settings': z.object({
  'serverUrl': z.string().readonly(),
  'username': z.string().readonly(),
  'accessMode': z.union([z.literal("all"), z.literal("allowlist")]).readonly(),
  'allowedRoots': z.array(z.string()).readonly(),
  'allowDelete': z.boolean().readonly(),
  'allowHttp': z.boolean().readonly(),
  'skipTlsVerify': z.boolean().readonly(),
}).readonly(),
})
const dsh_nextcloud_nextcloudSettings_save_result$schema = z.object({
  'settings': z.object({
  'serverUrl': z.string().readonly(),
  'username': z.string().readonly(),
  'accessMode': z.union([z.literal("all"), z.literal("allowlist")]).readonly(),
  'allowedRoots': z.array(z.string()).readonly(),
  'allowDelete': z.boolean().readonly(),
  'allowHttp': z.boolean().readonly(),
  'skipTlsVerify': z.boolean().readonly(),
}).readonly(),
})
const dsh_nextcloud_nextcloudSettings_testConnection_result$schema = z.object({
  'ok': z.literal(true).readonly(),
  'root': z.string().readonly(),
})

export const TYPERT = {
  package: 'dsh-nextcloud',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-nextcloud#nextcloudSettings/load',
      service: 'nextcloudSettings',
      namespace: 'nextcloudSettings',
      method: 'load',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-nextcloud/remote-types#NextcloudSettingsSaveResult',
        schema: dsh_nextcloud_nextcloudSettings_load_result$schema,
      },
      sourceLocation: {"file":"packages/nextcloud/src/index.ts","line":32,"column":19},
    },
    {
      id: 'dsh-nextcloud#nextcloudSettings/save',
      service: 'nextcloudSettings',
      namespace: 'nextcloudSettings',
      method: 'save',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-nextcloud/remote-types#NextcloudSettingsSaveRequest',
            schema: dsh_nextcloud_nextcloudSettings_save_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-nextcloud/remote-types#NextcloudSettingsSaveResult',
        schema: dsh_nextcloud_nextcloudSettings_save_result$schema,
      },
      sourceLocation: {"file":"packages/nextcloud/src/index.ts","line":38,"column":19},
    },
    {
      id: 'dsh-nextcloud#nextcloudSettings/testConnection',
      service: 'nextcloudSettings',
      namespace: 'nextcloudSettings',
      method: 'testConnection',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-nextcloud/remote-types#NextcloudConnectionResult',
        schema: dsh_nextcloud_nextcloudSettings_testConnection_result$schema,
      },
      sourceLocation: {"file":"packages/nextcloud/src/index.ts","line":44,"column":35},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
