/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { NextcloudConnectionResult, NextcloudSettingsSaveRequest, NextcloudSettingsSaveResult } from 'dsh-nextcloud/remote-types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6e657874636c6f756453657474696e6773 {
    load: () => Promise<RemoteResult<NextcloudSettingsSaveResult>>
    save: (request: NextcloudSettingsSaveRequest) => Promise<RemoteResult<NextcloudSettingsSaveResult>>
    testConnection: () => Promise<RemoteResult<NextcloudConnectionResult>>
  }
  interface TypertRemoteMap {
    'nextcloudSettings/load': () => Promise<RemoteResult<NextcloudSettingsSaveResult>>
    'nextcloudSettings/save': (request: NextcloudSettingsSaveRequest) => Promise<RemoteResult<NextcloudSettingsSaveResult>>
    'nextcloudSettings/testConnection': () => Promise<RemoteResult<NextcloudConnectionResult>>
  }
  interface TypertRemoteNamespaceMap {
    'nextcloudSettings': TypertRemoteNamespace$6e657874636c6f756453657474696e6773
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
