/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { WeComAuthSnapshot } from 'dsh-wecom/remote-types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7765636f6d41757468 {
    cancel: () => Promise<RemoteResult<WeComAuthSnapshot>>
    connect: () => Promise<RemoteResult<WeComAuthSnapshot>>
    deleteAuthorization: (confirmed: boolean) => Promise<RemoteResult<WeComAuthSnapshot>>
    refresh: () => Promise<RemoteResult<WeComAuthSnapshot>>
    status: () => Promise<RemoteResult<WeComAuthSnapshot>>
  }
  interface TypertRemoteMap {
    'wecomAuth/cancel': () => Promise<RemoteResult<WeComAuthSnapshot>>
    'wecomAuth/connect': () => Promise<RemoteResult<WeComAuthSnapshot>>
    'wecomAuth/deleteAuthorization': (confirmed: boolean) => Promise<RemoteResult<WeComAuthSnapshot>>
    'wecomAuth/refresh': () => Promise<RemoteResult<WeComAuthSnapshot>>
    'wecomAuth/status': () => Promise<RemoteResult<WeComAuthSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'wecomAuth': TypertRemoteNamespace$7765636f6d41757468
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
