/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_wecom_wecomAuth_cancel_result$schema = z.union([z.object({
  'state': z.literal("unauthorized").readonly(),
}), z.object({
  'state': z.literal("generating_qr").readonly(),
}), z.object({
  'state': z.literal("awaiting_scan").readonly(),
  'qrDataUrl': z.string().readonly(),
}), z.object({
  'state': z.literal("authorized").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'state': z.literal("refreshing_schema").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'state': z.literal("ready").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'toolCount': z.number().readonly(),
}), z.object({
  'state': z.literal("sync_failed").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'message': z.string().readonly(),
}), z.object({
  'state': z.literal("deleting").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
})])
const dsh_wecom_wecomAuth_connect_result$schema = z.union([z.object({
  'state': z.literal("unauthorized").readonly(),
}), z.object({
  'state': z.literal("generating_qr").readonly(),
}), z.object({
  'state': z.literal("awaiting_scan").readonly(),
  'qrDataUrl': z.string().readonly(),
}), z.object({
  'state': z.literal("authorized").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'state': z.literal("refreshing_schema").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'state': z.literal("ready").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'toolCount': z.number().readonly(),
}), z.object({
  'state': z.literal("sync_failed").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'message': z.string().readonly(),
}), z.object({
  'state': z.literal("deleting").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
})])
const dsh_wecom_wecomAuth_deleteAuthorization_parameter_0$schema = z.boolean()
const dsh_wecom_wecomAuth_deleteAuthorization_result$schema = z.union([z.object({
  'state': z.literal("unauthorized").readonly(),
}), z.object({
  'state': z.literal("generating_qr").readonly(),
}), z.object({
  'state': z.literal("awaiting_scan").readonly(),
  'qrDataUrl': z.string().readonly(),
}), z.object({
  'state': z.literal("authorized").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'state': z.literal("refreshing_schema").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'state': z.literal("ready").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'toolCount': z.number().readonly(),
}), z.object({
  'state': z.literal("sync_failed").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'message': z.string().readonly(),
}), z.object({
  'state': z.literal("deleting").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
})])
const dsh_wecom_wecomAuth_refresh_result$schema = z.union([z.object({
  'state': z.literal("unauthorized").readonly(),
}), z.object({
  'state': z.literal("generating_qr").readonly(),
}), z.object({
  'state': z.literal("awaiting_scan").readonly(),
  'qrDataUrl': z.string().readonly(),
}), z.object({
  'state': z.literal("authorized").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'state': z.literal("refreshing_schema").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'state': z.literal("ready").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'toolCount': z.number().readonly(),
}), z.object({
  'state': z.literal("sync_failed").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'message': z.string().readonly(),
}), z.object({
  'state': z.literal("deleting").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
})])
const dsh_wecom_wecomAuth_status_result$schema = z.union([z.object({
  'state': z.literal("unauthorized").readonly(),
}), z.object({
  'state': z.literal("generating_qr").readonly(),
}), z.object({
  'state': z.literal("awaiting_scan").readonly(),
  'qrDataUrl': z.string().readonly(),
}), z.object({
  'state': z.literal("authorized").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'state': z.literal("refreshing_schema").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'state': z.literal("ready").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'toolCount': z.number().readonly(),
}), z.object({
  'state': z.literal("sync_failed").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'message': z.string().readonly(),
}), z.object({
  'state': z.literal("deleting").readonly(),
  'botId': z.union([z.undefined(), z.string()]).readonly().optional(),
})])

export const TYPERT = {
  package: 'dsh-wecom',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-wecom#wecomAuth/cancel',
      service: 'wecomAuth',
      namespace: 'wecomAuth',
      method: 'cancel',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-wecom/remote-types#WeComAuthSnapshot',
        schema: dsh_wecom_wecomAuth_cancel_result$schema,
      },
      sourceLocation: {"file":"packages/wecom/src/index.ts","line":44,"column":21},
    },
    {
      id: 'dsh-wecom#wecomAuth/connect',
      service: 'wecomAuth',
      namespace: 'wecomAuth',
      method: 'connect',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-wecom/remote-types#WeComAuthSnapshot',
        schema: dsh_wecom_wecomAuth_connect_result$schema,
      },
      sourceLocation: {"file":"packages/wecom/src/index.ts","line":43,"column":22},
    },
    {
      id: 'dsh-wecom#wecomAuth/deleteAuthorization',
      service: 'wecomAuth',
      namespace: 'wecomAuth',
      method: 'deleteAuthorization',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'confirmed',
          wire: 'confirmed',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-wecom#wecomAuth/deleteAuthorization:confirmed',
            schema: dsh_wecom_wecomAuth_deleteAuthorization_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-wecom/remote-types#WeComAuthSnapshot',
        schema: dsh_wecom_wecomAuth_deleteAuthorization_result$schema,
      },
      sourceLocation: {"file":"packages/wecom/src/index.ts","line":46,"column":34},
    },
    {
      id: 'dsh-wecom#wecomAuth/refresh',
      service: 'wecomAuth',
      namespace: 'wecomAuth',
      method: 'refresh',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-wecom/remote-types#WeComAuthSnapshot',
        schema: dsh_wecom_wecomAuth_refresh_result$schema,
      },
      sourceLocation: {"file":"packages/wecom/src/index.ts","line":45,"column":22},
    },
    {
      id: 'dsh-wecom#wecomAuth/status',
      service: 'wecomAuth',
      namespace: 'wecomAuth',
      method: 'status',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-wecom/remote-types#WeComAuthSnapshot',
        schema: dsh_wecom_wecomAuth_status_result$schema,
      },
      sourceLocation: {"file":"packages/wecom/src/index.ts","line":42,"column":21},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
