/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_plugin_manager_pluginManager_append_parameter_0$schema = z.object({
  'uploadId': z.string().readonly(),
  'index': z.number().readonly(),
  'bytesBase64': z.string().readonly(),
})
const dsh_plugin_manager_pluginManager_append_result$schema = z.object({
  'received': z.number().readonly(),
  'size': z.number().readonly(),
})
const dsh_plugin_manager_pluginManager_begin_parameter_0$schema = z.object({
  'fileName': z.string().readonly(),
  'size': z.number().readonly(),
})
const dsh_plugin_manager_pluginManager_begin_result$schema = z.object({
  'uploadId': z.string().readonly(),
  'chunkSize': z.number().readonly(),
})
const dsh_plugin_manager_pluginManager_cancel_parameter_0$schema = z.object({
  'uploadId': z.string().readonly(),
})
const dsh_plugin_manager_pluginManager_cancel_result$schema = z.object({
  'cancelled': z.literal(true).readonly(),
})
const dsh_plugin_manager_pluginManager_finish_parameter_0$schema = z.object({
  'uploadId': z.string().readonly(),
})
const dsh_plugin_manager_pluginManager_finish_result$schema = z.object({
  'action': z.union([z.literal("install"), z.literal("upgrade"), z.literal("reinstall")]).readonly(),
  'packageName': z.string().readonly(),
  'version': z.string().readonly(),
  'requiresRestart': z.literal(true).readonly(),
})
const dsh_plugin_manager_pluginManager_list_result$schema = z.object({
  'entries': z.array(z.object({
  'packageName': z.string().readonly(),
  'version': z.string().readonly(),
  'canUninstall': z.boolean().readonly(),
})).readonly(),
})
const dsh_plugin_manager_pluginManager_uninstall_parameter_0$schema = z.object({
  'packageName': z.string().readonly(),
  'expectedVersion': z.string().readonly(),
})
const dsh_plugin_manager_pluginManager_uninstall_result$schema = z.object({
  'packageName': z.string().readonly(),
  'version': z.string().readonly(),
  'requiresRestart': z.literal(true).readonly(),
})

export const TYPERT = {
  package: 'dsh-plugin-manager',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-plugin-manager#pluginManager/append',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'append',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-plugin-manager/remote-types#AppendChunkWireRequest',
            schema: dsh_plugin_manager_pluginManager_append_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-plugin-manager/remote-types#UploadProgressWireResult',
        schema: dsh_plugin_manager_pluginManager_append_result$schema,
      },
      sourceLocation: {"file":"packages/manager/src/index.ts","line":42,"column":3},
    },
    {
      id: 'dsh-plugin-manager#pluginManager/begin',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'begin',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-plugin-manager/remote-types#BeginUploadWireRequest',
            schema: dsh_plugin_manager_pluginManager_begin_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-plugin-manager/remote-types#BeginUploadWireResult',
        schema: dsh_plugin_manager_pluginManager_begin_result$schema,
      },
      sourceLocation: {"file":"packages/manager/src/index.ts","line":37,"column":3},
    },
    {
      id: 'dsh-plugin-manager#pluginManager/cancel',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'cancel',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-plugin-manager/remote-types#UploadWireRequest',
            schema: dsh_plugin_manager_pluginManager_cancel_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-plugin-manager/remote-types#CancelUploadWireResult',
        schema: dsh_plugin_manager_pluginManager_cancel_result$schema,
      },
      sourceLocation: {"file":"packages/manager/src/index.ts","line":56,"column":3},
    },
    {
      id: 'dsh-plugin-manager#pluginManager/finish',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'finish',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-plugin-manager/remote-types#UploadWireRequest',
            schema: dsh_plugin_manager_pluginManager_finish_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-plugin-manager/remote-types#InstallResult',
        schema: dsh_plugin_manager_pluginManager_finish_result$schema,
      },
      sourceLocation: {"file":"packages/manager/src/index.ts","line":51,"column":3},
    },
    {
      id: 'dsh-plugin-manager#pluginManager/list',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-plugin-manager/remote-types#ListPluginsResult',
        schema: dsh_plugin_manager_pluginManager_list_result$schema,
      },
      sourceLocation: {"file":"packages/manager/src/index.ts","line":32,"column":9},
    },
    {
      id: 'dsh-plugin-manager#pluginManager/uninstall',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'uninstall',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-plugin-manager/remote-types#UninstallWireRequest',
            schema: dsh_plugin_manager_pluginManager_uninstall_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-plugin-manager/remote-types#UninstallResult',
        schema: dsh_plugin_manager_pluginManager_uninstall_result$schema,
      },
      sourceLocation: {"file":"packages/manager/src/index.ts","line":61,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
