/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AppendChunkWireRequest, BeginUploadWireRequest, BeginUploadWireResult, CancelUploadWireResult, InstallResult, ListPluginsResult, UninstallResult, UninstallWireRequest, UploadProgressWireResult, UploadWireRequest } from 'dsh-plugin-manager/remote-types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$706c7567696e4d616e61676572 {
    append: (request: AppendChunkWireRequest) => Promise<RemoteResult<UploadProgressWireResult>>
    begin: (request: BeginUploadWireRequest) => Promise<RemoteResult<BeginUploadWireResult>>
    cancel: (request: UploadWireRequest) => Promise<RemoteResult<CancelUploadWireResult>>
    finish: (request: UploadWireRequest, signal?: AbortSignal) => Promise<RemoteResult<InstallResult>>
    list: () => Promise<RemoteResult<ListPluginsResult>>
    uninstall: (request: UninstallWireRequest, signal?: AbortSignal) => Promise<RemoteResult<UninstallResult>>
  }
  interface TypertRemoteMap {
    'pluginManager/append': (request: AppendChunkWireRequest) => Promise<RemoteResult<UploadProgressWireResult>>
    'pluginManager/begin': (request: BeginUploadWireRequest) => Promise<RemoteResult<BeginUploadWireResult>>
    'pluginManager/cancel': (request: UploadWireRequest) => Promise<RemoteResult<CancelUploadWireResult>>
    'pluginManager/finish': (request: UploadWireRequest, signal?: AbortSignal) => Promise<RemoteResult<InstallResult>>
    'pluginManager/list': () => Promise<RemoteResult<ListPluginsResult>>
    'pluginManager/uninstall': (request: UninstallWireRequest, signal?: AbortSignal) => Promise<RemoteResult<UninstallResult>>
  }
  interface TypertRemoteNamespaceMap {
    'pluginManager': TypertRemoteNamespace$706c7567696e4d616e61676572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
