/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_confluence_confluenceSettings_credentialRef_parameter_0$schema = z.string()
const dsh_confluence_confluenceSettings_credentialRef_result$schema = z.object({
  'patRef': z.string(),
})
const dsh_confluence_confluenceSettings_load_result$schema = z.object({
  'settings': z.object({
  'baseUrl': z.string(),
  'allowAllSpaces': z.boolean(),
  'allowedSpaceKeys': z.array(z.string()),
}),
  'patRef': z.string(),
})
const dsh_confluence_confluenceSettings_save_parameter_0$schema = z.object({
  'settings': z.object({
  'baseUrl': z.string(),
  'allowAllSpaces': z.boolean(),
  'allowedSpaceKeys': z.array(z.string()),
}),
})
const dsh_confluence_confluenceSettings_save_result$schema = z.object({
  'settings': z.object({
  'baseUrl': z.string(),
  'allowAllSpaces': z.boolean(),
  'allowedSpaceKeys': z.array(z.string()),
}),
  'patRef': z.string(),
})
const dsh_confluence_confluenceSettings_testConnection_parameter_0$schema = z.object({
  'baseUrl': z.string(),
  'allowAllSpaces': z.boolean(),
  'allowedSpaceKeys': z.array(z.string()),
})
const dsh_confluence_confluenceSettings_testConnection_result$schema = z.object({
  'ok': z.literal(true),
  'version': z.string(),
  'buildNumber': z.number(),
  'verifiedSpaces': z.array(z.string()),
})

export const TYPERT = {
  package: 'dsh-confluence',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-confluence#confluenceSettings/credentialRef',
      service: 'confluenceSettings',
      namespace: 'confluenceSettings',
      method: 'credentialRef',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'baseUrl',
          wire: 'baseUrl',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-confluence#confluenceSettings/credentialRef:baseUrl',
            schema: dsh_confluence_confluenceSettings_credentialRef_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-confluence/remote-types#ConfluenceCredentialRefResult',
        schema: dsh_confluence_confluenceSettings_credentialRef_result$schema,
      },
      sourceLocation: {"file":"packages/confluence/src/index.ts","line":39,"column":3},
    },
    {
      id: 'dsh-confluence#confluenceSettings/load',
      service: 'confluenceSettings',
      namespace: 'confluenceSettings',
      method: 'load',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-confluence/remote-types#ConfluenceSettingsSaveResult',
        schema: dsh_confluence_confluenceSettings_load_result$schema,
      },
      sourceLocation: {"file":"packages/confluence/src/index.ts","line":31,"column":3},
    },
    {
      id: 'dsh-confluence#confluenceSettings/save',
      service: 'confluenceSettings',
      namespace: 'confluenceSettings',
      method: 'save',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-confluence/remote-types#ConfluenceSettingsSaveRequest',
            schema: dsh_confluence_confluenceSettings_save_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-confluence/remote-types#ConfluenceSettingsSaveResult',
        schema: dsh_confluence_confluenceSettings_save_result$schema,
      },
      sourceLocation: {"file":"packages/confluence/src/index.ts","line":42,"column":9},
    },
    {
      id: 'dsh-confluence#confluenceSettings/testConnection',
      service: 'confluenceSettings',
      namespace: 'confluenceSettings',
      method: 'testConnection',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'settings',
          wire: 'settings',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-confluence/settings#ConfluenceSettings',
            schema: dsh_confluence_confluenceSettings_testConnection_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-confluence/remote-types#ConfluenceConnectionResult',
        schema: dsh_confluence_confluenceSettings_testConnection_result$schema,
      },
      sourceLocation: {"file":"packages/confluence/src/index.ts","line":49,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
