/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ConfluenceConnectionResult, ConfluenceCredentialRefResult, ConfluenceSettingsSaveRequest, ConfluenceSettingsSaveResult } from 'dsh-confluence/remote-types'
import type { ConfluenceSettings } from 'dsh-confluence/settings'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$636f6e666c75656e636553657474696e6773 {
    credentialRef: (baseUrl: string) => Promise<RemoteResult<ConfluenceCredentialRefResult>>
    load: () => Promise<RemoteResult<ConfluenceSettingsSaveResult>>
    save: (request: ConfluenceSettingsSaveRequest) => Promise<RemoteResult<ConfluenceSettingsSaveResult>>
    testConnection: (settings: ConfluenceSettings) => Promise<RemoteResult<ConfluenceConnectionResult>>
  }
  interface TypertRemoteMap {
    'confluenceSettings/credentialRef': (baseUrl: string) => Promise<RemoteResult<ConfluenceCredentialRefResult>>
    'confluenceSettings/load': () => Promise<RemoteResult<ConfluenceSettingsSaveResult>>
    'confluenceSettings/save': (request: ConfluenceSettingsSaveRequest) => Promise<RemoteResult<ConfluenceSettingsSaveResult>>
    'confluenceSettings/testConnection': (settings: ConfluenceSettings) => Promise<RemoteResult<ConfluenceConnectionResult>>
  }
  interface TypertRemoteNamespaceMap {
    'confluenceSettings': TypertRemoteNamespace$636f6e666c75656e636553657474696e6773
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
